spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1089873847707-fmli8704l4fr0cdv042qda8jmpd8ogu0.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          kakao:
            client-id: 3447dc8e79b235f2e099eb01a8832a4e
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao

          naver:
            client-id: qQnEPGC5Ry1xwwI5BqNR
            client-secret: GynKq0tJNz
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver

        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response