spring:
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sksms331
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1089873847707-fmli8704l4fr0cdv042qda8jmpd8ogu0.apps.googleusercontent.com
            client-secret: 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

  session:
    store-type: jdbc
    # spring.session.jdbc.initialize-schema: always 설정이 있어야만
    # JPA 가 자동으로 세션 저장용 테이블을 생성한다.
    jdbc:
      initialize-schema: always

  messages:
    basename:
      - messages
      - errors



custom:
  oauth2:
    kakao:
      client-id: 88a081241234cfacbedef7018ac451316f3
      client-secret: jpXULoEzrasfawegsqYXlRLyyOHn2i60q
    naver:
      client-id: B5yvH3Zaweyawerawwe6repj4z0L
      client-secret: sArXFasdfawef


logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql: trace
